[package]
name = "shit-chat-says"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "chain"
path = "src/chain/lib.rs"

[[bin]]
name = "train"
path = "src/train/main.rs"

[[bin]]
name = "gen"
path = "src/gen/main.rs"

[[bin]]
name = "collector"
path = "src/collector/main.rs"

[[bin]]
name = "chat"
path = "src/chat/main.rs"

[[bench]]
name = "chains"
harness = false

[dependencies]
markov = "1.1.0"
anyhow = "1.0.45"
rustyline = "9.0.0"
tokio = { version = "1.13.0", features = ["full"] }
twitch = { git = "https://github.com/jprochazk/twitch-rs.git" }
env_logger = "0.9.0"
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.69"
chrono = "0.4.19"
crossbeam-channel = "0.5.1"
walkdir = "2.3.2"
ahash = "0.7.6"
rand = "0.8.4"
string-interner = "0.14.0"
itertools = "0.10.1"

[dev-dependencies]
criterion = "0.3.5"
serde_yaml = "0.8.21"
