[package]
name = "scs-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
anyhow = "1.0.48"
humantime-serde = "1.0.1"
log = "0.4.14"
chrono = "0.4.19"
regex = "1.5.4"
