version: "3.7"

services:
  collector:
    restart: always
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: runtime
    entrypoint:
      - /binaries/collector
    command: /config/collector.json
    volumes:
      - ../logs:/logs
      - ../config:/config

  chat:
    restart: always
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: runtime
    entrypoint:
      - /binaries/chat
    command: /config/chat.json
    volumes:
      - ../models:/models
      - ../config:/config

  train:
    profiles:
      - training
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: trainer
    environment:
      - TRAIN_CONFIG=/config/train.json
    volumes:
      - ../logs:/logs
      - ../models:/models
      - ../config:/config
