version: "3.7"

services:
  collector:
    restart: always
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    entrypoint:
      - /binaries/collector
    command: /config/collector.json
    volumes:
      - ../logs:/logs
      - ../config:/config

  chat:
    restart: always
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    entrypoint:
      - /binaries/chat
    command: /config/chat.json
    environment:
      - SCS_MODEL_PATH=/models/model.yaml
    volumes:
      - ../models:/models
      - ../config:/config

  train:
    profiles:
      - training
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    entrypoint:
      - /binaries/train
    environment:
      - SCS_INPUT_DIR=/logs
      - SCS_MODEL_PATH=/models/model.yaml
    volumes:
      - ../logs:/logs
      - ../models:/models
